- examples/odm_mysql/config.cfg
- examples/odm_mysql/odm_dao.py
- examples/odm_mysql/runserver.py
- examples/odm_mysql/sqlalch_odm_models.py
MySQL wants lowercase table names (if software can be said to have desires, hopes, and wishes). It needs a better way to set the configuration, but at least this code does the heavy lifting.
> Add support for lowercase table names for mysql

- .travis.yml
- MANIFEST.in
- requirements-dev.txt
- requirements.txt
- setup.py
- test/test_wofpy_soap.py
> Leaner Travis-CI configuration.

- .travis.yml
- docs/timetest.py
- requirements-dev.txt
- test/test_wofpy_soap.py
- wof/examples/flask/barebones/runserver_LCM.py
- wof/examples/flask/cbi/runserver_cbi.py
- wof/examples/flask/csv_server/runserver_csv.py
- wof/examples/flask/csv_server/runserver_test_multiple.py
- wof/examples/flask/csv_tutorial/solution/runserver_csv.py
- wof/examples/flask/csv_tutorial/tutorial/runserver_csv.py
- wof/examples/flask/odm2/measurement/runserver_odm2_measurement.py
- wof/examples/flask/odm2/runserver_multiple.py
- wof/examples/flask/odm2/timeseries/runserver_odm2_timeseries.py
- wof/examples/flask/odm_1_1/runserver_odm_1_1.py
- wof/examples/flask/runserver_multiple.py
- wof/examples/flask/swis/runserver_swis.py
Fix some remaining print statements, fix some `.format` misuse, adds extra coding standards warnings to help us avoid regressions in the future.
> Print stataments

- test/runserver_test.py
- test/test_cbi_dao.py
- test/test_cbi_parser.py
- test/test_dao.py
- test/test_odm2_dao_sqlite.py
- test/test_odm_dao.py
- test/test_swis_dao.py
- test/test_wof.py
- test/test_wofpy_soap.py
> Remove ../implementations/ from references from tests

- .travis.yml
Run "verbose" py.test and fix a `flake8` typo.
> Verbose tests

- wof/__init__.py
- wof/core_1_0.py
- wof/core_1_1.py
- wof/flask/__init__.py
This will hopefully fix the import core failures during travis ci build.
> Fixed core, waterml, and config imports

- wof/WaterML.py
@lsetiawan this is my last PR for today (time to clock out here) but I have more for tomorrow.
Feel free to ping me for review and I will take a look early tomorrow before sending more PRs.
> Fix Exceptions

- test/test_cbi_dao.py
- test/test_cbi_parser.py
- test/test_odm2_dao_sqlite.py
- test/test_swis_dao.py
- test/test_wofpy_soap.py
- wof/examples/flask/barebones/LCM_dao.py
- wof/examples/flask/barebones/runserver_LCM.py
- wof/examples/flask/cbi/build_cbi_cache.py
- wof/examples/flask/cbi/cbi_dao.py
- wof/examples/flask/cbi/cbi_sos_parser.py
- wof/examples/flask/cbi/runserver_cbi.py
- wof/examples/flask/csv_server/csv_dao.py
- wof/examples/flask/csv_server/runserver_csv.py
- wof/examples/flask/csv_server/runserver_test_multiple.py
- wof/examples/flask/csv_tutorial/solution/csv_dao.py
- wof/examples/flask/csv_tutorial/solution/runserver_csv.py
- wof/examples/flask/csv_tutorial/tutorial/runserver_csv.py
- wof/examples/flask/odm2/measurement/odm2_measurement_dao.py
- wof/examples/flask/odm2/measurement/runserver_odm2_measurement.py
- wof/examples/flask/odm2/runserver_multiple.py
- wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py
- wof/examples/flask/odm2/timeseries/runserver_odm2_timeseries.py
- wof/examples/flask/odm_1_1/odm_dao.py
- wof/examples/flask/odm_1_1/runserver_odm_1_1.py
- wof/examples/flask/runserver_multiple.py
- wof/examples/flask/swis/runserver_swis.py
- wof/examples/flask/swis/swis_dao.py
This should fix import errors in a bunch of the test scripts
> Fix import errors within test scripts

- wof/WofWsdls.py
- wof/__init__.py
- wof/apps/spyned_1_0.py
- wof/apps/spyned_1_1.py
- wof/core.py
- wof/core_1_0.py
- wof/core_1_1.py
- wof/dao.py
- wof/models.py
- wof/wofpy_config.py
@lsetiawan can you review and merge this one? Unfortunately the changes are massive and I am not nearly done :weary: 
But I don't want to do everything in one go to avoid disrupting other PRs with unnecessary rebases.
PS: I won't send another `flake8` PR today.
> Some flake8 fixes.

- examples_may_not_work/flask/runserver_multiple.py
- wof/__init__.py
- wof/core.py
- wof/examples/flask/odm2/measurement/runserver_odm2_measurement.py
- wof/examples/flask/odm2/runserver_multiple.py
- wof/examples/flask/runserver_multiple.py
@emiliom this does not assure that the code is compatible with Windows nor that should hold us from issuing a new release. But having this merged is nice not only for Windows sake's but for overall code readability since it defines the template path in a single place.
> Windows friendly paths

- wof/WaterML.py
Fix a few left-over old, and invalid, exception syntax.
> Fix exceptions syntax

- README.md
- appveyor.yml
- conda.recipe/meta.yaml
This PR adds a testing framework for Windows.
> AppVeyor configuration.

- wof/examples/flask/odm2/timeseries/__init__.py
- wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py
- wof/examples/flask/odm2/timeseries/runserver_odm2_timeseries.py
- wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py
@ocefpaf I did some clean up for timeseries examples so that at least now `timeseries` for `wofpy_config` will have clean code. Hopefully I didn't miss or break anything (will test and confirm).
> Pep8 cleanup

- docs/WOFpyODM2LBR_installation.md
New installation documentation. Please review and let me know if it makes sense. Thanks.
> New Install Documentation

- wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py
- wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py
This PR: 
- Updates the `odm2timeseries` dao to query Affiliations better. #129 
- Provide Handling for Affiliations https://github.com/ODM2/WOFpy/issues/128#issue-230810014 number 3
> Update DAO and WOF Timeseries Models to handle Affiliations better

- wof/core_1_1.py
This PR will fix https://github.com/ODM2/WOFpy/issues/129
Though this is not a clean fix, more development is needed on https://github.com/ODM2/WOFpy/blob/master/wof/WaterML_1_1.py#L4373, It is currently expecting a list of email... Not sure if this is how it's supposed to be.
For now the fix on core by passing email, phone, and address as a list works.
> Update handling of contactInformation

- MANIFEST.in
- wof/wofpy_config.py
~~Not ready for review/merge yet!~~
(Closes #132 and #72 ?)
> CLI updates

- docs/WOFpyODM2LBR_installation.md
Edited documentation to include single server setup...
~~Just realized I didn't include a TOC, don't merge yet.~~
> Edited documentation

- setup.py
Address @emiliom's comment from https://github.com/ODM2/WOFpy/issues/128#issuecomment-307896499
> remove odm2api pinned from git

- wof/wofpy_config.py
Implements https://github.com/ODM2/WOFpy/issues/139#issuecomment-307894647
There is a complicated logic there and I would like to look at it again tomorrow with fresh eyes before this is merged. Submitting the PR today just to get some input from @emiliom and @lsetiawan.
> overwrite options

- wof/wofpy_config.py
Just little spelling error fixes.
> Fix little spelling errors

- wof/wofpy_config.py
Fix https://github.com/ODM2/WOFpy/issues/139#issuecomment-308216859
> fix verbose mode

- setup.py
- wof/WaterML.py
> fix versioneer cmdclass

- wof/WaterML_1_1.py
- wof/apps/spyned_1_1.py
This PR addresses https://github.com/ODM2/WOFpy/issues/148.
This way of handling unicode was [suggested](https://github.com/ODM2/WOFpy/issues/148#issuecomment-314585433) by @ocefpaf.
Still waiting for PR https://github.com/ODM2/WOFpy/pull/156 to have the tests for unicodes.
> Better unicode handling.

- wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py
- wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py
This addresses `dataType` and `generalCategory` for #152.
> Fix dataType and add generalCategory

- wof/core_1_1.py
- wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py
- wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py
- wof/models.py
This PR addresses #162. `agencyName` and `agencyCode` should show up when organizationtype matches either `Government agency` or `Research agency`.
> Expose agency

- wof/core_1_1.py
This PR exposes method, source, and qualitycontrollevel within each series during `GetSiteInfo` request. This partially relate to #162
> Expose method, source, and qualitycontrollevel

- .travis.yml
- test/test_cli.py
This change should fix the failure (or at least make reveal a bug :smile:) that @lsetiawan observed in https://github.com/ODM2/WOFpy/pull/177#issuecomment-326120952
> split cbi scenario and reduce fixture scope

- wof/examples/flask/odm2/timeseries/odm2_config_timeseries.cfg
This PR relates to #191. I've changed the default url pattern to match what's actually being used. Haven't figured out automation yet though..
> Update default service wsdl url pattern.

- test/test_dao_1_1.py
- wof/WaterML_1_1.py
- wof/apps/spyned_1_1.py
This PR continues on #188 and hopefully address #148. Now the test and actual application uses the same way of encoding/decoding the content from the database.
> Hopefully last whack-a-unicode

- wof/WaterML_1_1.py
This PR addresses #196 errors that @miguelcleon is seeing in his database. I've tested it with the ipynb that @emiliom gave with the database backup, and it worked! Hopefully you will experience the same @miguelcleon.
> Handle None Contact Info that causes error

- README.md
I am moving the ODM2 projects to the ODM2 AppVeyor account.
In theory everyone in the ODM2 org, with an AppVeyor account attached to their GitHub account,
should be able to manage AppVeyor jobs (cancel, restart, etc).
> New badge AppVeyor badge

- wof/core.py
- wof/core_1_0.py
- wof/core_1_1.py
- wof/examples/flask/odm2/timeseries/odm2_config_timeseries.cfg
- wof/flask/__init__.py
- wof/flask/templates/index.html
- wof/flask/templates/index_1_0.html
- wof/flask/templates/index_1_1.html
- wof/flask/templates/index_2.html
This PR adds styling to WOFpy. This relates to #167. It is not ready for merging yet, wording needs to be fixed and some mechanics in the code to get some of the information needs to be added.
> Add style to WOFpy

- wof/core_1_1.py
This PR should address #209. It aligns code in value elements with ID and Code. @emiliom I'll send you sample xml. Thanks.
> Align code id/code in value elements

- wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py
- wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py
This PR adds Timescale within `GetSiteInfo`. This doesn't fix probles with WaterML R in issue https://github.com/BiG-CZ/wshp2017_tutorial_content/issues/7
> GetSiteInfo TimeScale Element Content

- wof/core_1_1.py
Small fix for qualitylevelcontrol code that I missed.
> Little fix to qualitycontrollevelcode

- docker_dev/README.md
- docker_dev/docker-compose.yml
- docker_dev/mysql/config-file.cnf
- docker_dev/scripts/setup-mysql.sh
- docker_dev/scripts/setup-server.sh
- docker_dev/scripts/start-server.sh
- docker_dev/scripts/wait-for-mysql.sh
- docker_dev/wofpy-server/Dockerfile
- docker_dev/wofpy-server/odm2_config_timeseries.cfg
This PR adds docker development setup!
> Add docker dev setup

- .travis.yml
> add docs section
