ODM2/WOFpy

.travis.yml, setup.py, test/runserver_test.py, test/test_cbi_dao.py, test/test_cbi_parser.py, test/test_dao.py, test/test_odm2_dao_sqlite.py, test/test_odm_dao.py, test/test_swis_dao.py, test/test_wof.py, test/test_wofpy_soap.py, wof/WaterML.py, wof/WaterML_1_1.py, wof/WofWsdls.py, wof/__init__.py, wof/apps/__init__.py, wof/apps/spyned_1_0.py, wof/apps/spyned_1_1.py, wof/apps/waterml2.py, wof/core.py, wof/core_1_0.py, wof/core_1_1.py, wof/dao.py, wof/examples/flask/runserver_multiple.py, wof/examples/flask/swis/swis_dao.py, wof/flask/__init__.py, wof/flask/config.py, wof/models.py
@emiliom this PR continues the work from #63 but with small increments to make it easier to review.
Here I only added the `from __future__ import (absolute_import, division, print_function)` that is needed to ensure Python 3 behavior in Python 2 code. what we need to have in mind before merging this:
- importing those does ano add any overhead to the library;
- it will make print statements an error making it easier to catch and fix those in the code;
- will force good practice relating to relative vs absolute imports;
- all divisions will be float and no longer depend on the number type.
=> add __future__ imports

.gitignore
Simple PR and easy merge. Just adds the `.cache` directory to the ignore list for when we run `py.test` locally.
=> Ignore pytest cache

test/test_wofpy_soap.py, wof/__init__.py, wof/apps/__init__.py, wof/apps/spyned_1_0.py, wof/apps/spyned_1_1.py, wof/apps/waterml2.py, wof/core.py, wof/core_1_0.py, wof/core_1_1.py, wof/flask/__init__.py, wof/flask/config.py
In this PR:
- `ConfigParser` when it is imported but unused;
- add a Python 2/3 `configparser` import;
- re-organize the imports at the top to place the internal imports at the bottom and make them easier to recognize.
=> Fix configparser imports

.travis.yml, test/test_wofpy_soap.py, wof/core.py, wof/examples/flask/barebones/LCM_dao.py, wof/examples/flask/cbi/cbi_dao.py, wof/examples/flask/swis/swis_dao.py
OK. Now it is really the last one of the day :smile: 
@lsetiawan, after reading a little I realized that installing `configparser` on Python 2 is the best way to go. the `try`/`except` clause is awkward and prevent people with `configparser` on Python 2 to use it.
=> Use configparser

test/test_xml/get_all_variables.xml, test/test_xml/get_one_variable.xml, test/test_xml/get_siteinfo_novar.xml, test/test_xml/get_values_encloses_por.xml
XML's have misspelled word `celcius` changing to `celsius` should make the tests pass.
=> Fix XML's causing tests to fail on test_wof

wof/core_1_1.py, wof/examples/flask/cbi/build_cbi_cache.py, wof/examples/flask/cbi/cbi_sos_parser.py
@lsetiawan while debugging the tests I found out a few `.format` calls that still had the `%s` in them.
I fixed all those that showed up with a grep search, even a commented out one, so we can proceed with the test debug.
=> Fix some .format

.travis.yml
@lsetiawan and @emiliom this PR implements what we just discussed in the call. It still run the `test_odm2_dao_sqlite.py` but `Travis-CI` won't rely on that test to return a green status.
We can change that as soon as we fix `test_odm2_dao_sqlite.py`.
=> skip test_odm2_dao_sqlite

.travis.yml, requirements-dev.txt
@lsetiawan and @emiliom I notice that `.travis.yml` may be used as "instructions" to get an environment for development. Because of that this PR uses the `conda-forge` channel with more care by not adding it to the `.condarc`. This ensure that people won't compromise their envs with package versions that may not be 100% compatible with `defaults` and `odm2`. (See http://conda-forge.github.io/docs/conda-forge_gotchas.html#using-multiple-channels for more info on the possible problems from mixing channels.)
=> Use conda-forge only for extra packages

requirements-dev.txt, requirements.txt, setup.py
@lsetiawan I re-organized the dependencies here to reflect the optional dependencies.
The current options are: `pip install wofpy[odm1,odm2,sqlite,server]`
Let me know if those makes sense and/or if we can merge a few of those to reduce the number of options to a minimum.
=> Handle optional dependencies.

wof/examples/flask/odm2/timeseries/odm2_config_timeseries.cfg, wof/examples/flask/odm2/timeseries/runserver_odm2_timeseries.py
This pull request would grab database connection information from configfile during runserver, eliminating `--connection` option that was previously there. I've also cleaned up the runserver code a bit, eliminating unused imports.
=> Implement database string connection in configfile

.travis.yml
Now that `test_odm2_dao_sqlite` is passing we don't need to split the test.
=> Update test matrix

wof/examples/flask/odm2/timeseries/runserver_odm2_timeseries.py
I modified the odm2 timeseries runserver, so that I can use for both development and production. @ocefpaf Let me know if I'm breaking Pep8 and if I do, how can I do better? Basically I need to get the app variable for wsgi to use, and the `argparse` stuff is for development user input. Thanks.
=> Modified runserver to be able to use in production

wof/core.py
`app` doesn't exist anywhere, also, templates under `wof/apps` is not installed with package, though `flask/templates` does.
=> Fix path to templates

docs/WOFpyODM2LBR_installation.md, wof/examples/flask/odm2/timeseries/runserver_multiple_odm2timeseries.py
The new `runserver_multiple_odm2timeseries.py` deploys wofpy that uses two ODM2 Timeseries DAO. Currently the script doesn't run straight up, since `.cfg` files that are in the script needs to be created. 
This PR also updates the documentation.
=> Created runserver script that deploys wofpy from 2 databases, both are timeseries.

wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py, wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py
This updates the `odm2timeseries` DAO and WOF model definitions to work with Postgresql in addition to MySQL and SQLite. Improvements are needed, definitely not perfect, but currently it works.
=> Update dao and WOF models for odm2timeseries

wof/WaterML.py, wof/WaterML_1_1.py, wof/examples/flask/odm_1_1/runserver_odm_1_1.py, wof/examples/production_configs/wsgi.py
May help with https://github.com/ODM2/WOFpy/issues/73#issuecomment-308821652
=> Use portable shebangs

.travis.yml, requirements-dev.txt, test/test_cli.py, wof/wofpy_config.py
Just should make future changes more robust and harder to break.
=> Add a few CLI tests

wof/flask/templates/index_1_1.html
This PR adds `GetVariables` in `../rest_1_1/` WOFpy REST sample page.
Adressing @emiliom comment: https://github.com/ODM2/WOFpy/issues/165#issuecomment-323417817
=> Add GetVariables to default HTML WOFpy REST 1.1 endpoint page

wof/core_1_1.py
This PR addresses #168. Now `siteProperty` is shown only when there is value in it. Also, `note` has been removed since it's deprecated from WaterML 1.1.
I have tested the response locally with ulmo for SOAP and REST request, and now Postgresql works, because the response is able to be parsed.
=> Fix logic for siteProperty

wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py
This PR addresses #172 by providing a handling on the error. It is not specific to any Exception so I think this might also addresses #150...
I tested this by deploying WOFpy then restarting the Database. Originally I would get `OperationalError`, but with the handling, the error is not seen.
=> Added function to handle errors in database interactions, making server more stable.

wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py
This PR addresses #157. Dao now can handle `mssql` when querying.
=> Add MSSQL handling for dao query

wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py
This is a follow up to #174 after @emiliom [comment yesterday](https://github.com/ODM2/WOFpy/pull/174#issuecomment-325868133)
=> Making engine check more pythonic

wof/core_1_1.py, wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py, wof/vocabularies.py
- Refactored vocabularies module to generalize the checkers and add additional, optional capabilities.
- Iplemented optional pass-through of CV terms (for ODM2 support) for some CVs. 
Starts addressing https://github.com/ODM2/WOFpy/issues/160; more work is needed, but @lsetiawan is working on that
=> Vocabulary handling overhaul to support ODM2 DAO needs

.travis.yml, wof/examples/flask/odm2/cvmap_wml_1_1.yml, wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py
This PR addresses #160. This adds CV mapping for `CensorCode`, `DataType`, and `SampleMedium`. Other mappings are still in progress. This method will only address the ODM2 vocabularies that are short. 
```xml
<variable>
<variableCode default="true" vocabulary="mysqlodm2timeseries" variableID="4">USU4</variableCode>
<variableName>Turbidity</variableName>
<valueType>Unknown</valueType>
<dataType>Unknown</dataType>
<generalCategory>Unknown</generalCategory>
<sampleMedium>Unknown</sampleMedium>
...
```
```xml
<variable>
<variableCode default="true" vocabulary="mysqlodm2timeseries" variableID="4">USU4</variableCode>
<variableName>Turbidity</variableName>
<valueType>Unknown</valueType>
<dataType>Average</dataType>
<generalCategory>Water Quality</generalCategory>
<sampleMedium>Surface …
```
=> Add cvmapping from ODM2 to WaterML1.1

wof/examples/flask/odm2/timeseries/odm2_timeseries_dao.py, wof/examples/flask/odm2/timeseries/sqlalch_odm2_models.py
Addresses CV handling problem described in https://github.com/ODM2/WOFpy/issues/160#issuecomment-326148477, where not all CV's in `GetSite*` responses were still not being populated, for the ODM2 timeseries DAO. Specifically, this:
- `GetSiteInfo` responses have "Unknown" values for `valueType`, `dataType` and `sampleMedium`, in both databases/endpoints.
Untested! @lsetiawan, please test it first.
=> Fixed Series/Site CV assignments for ODM2 timeseries DAO

setup.py, wof/examples/flask/odm2/cvmap_wml_1_1.yml
Final changes before issuing the new release.
- Updated setup.py metadata (maintainer, keywords, and classifiers > Development Status)
- Refined (finalized) ODM2 DAO vocabulary mappings to `samplemedium` WaterML 1.1 CVs (in `cvmap_wml_1_1.yml` yaml file)
=> Updated setup.py metadata and samplemedium ODM2-WaterML1.1 CV mapping

test/test_cli.py, wof/wofpy_config.py
@lsetiawan ignore this for a while. I am just testing to see if I can get it to fail.
=> Test if mode is unique

docs/WOFpy_ODM2_SOAPandREST_Tests.ipynb
This PR addresses https://github.com/ODM2/WOFpy/issues/166#issuecomment-326414279. The Jupyter Notebook that runs some test requests to the "live" WOFpy instance on the clouds has been updated to test the latest release. The instance has also been updated to version 2.2.0.
=> Update SOAPandREST Tests ipynb

wof/examples/flask/odm2/timeseries/odm2_config_timeseries.cfg
I got some troubles about multi-thread of SQLite sometimes when I run the the example with the configuration file.
Even WOFpy web service was not working well when I wanted to get values of specific time period.
The error(e.g. Not Found error) was not occurred anymore after adding 'check_same_thread=False' part at the last line.
=> Add an option to connection_String of .cfg file

.travis.yml
@lsetiawan this is not ready yet and I'll need your help to continue.
For now this PR only adds the `mysql` and `postgresql` services.
Below you'll find the script we have in `odm2api`. Not sure how to edit that to provide a similar functionality for `WOFpy`. So here are my questions:
- do we need both `mysql` and `postgresql` or can we start with one and expand to more testing later?
- I recall that we had to enable `sudo` in `odm2api`, can we avoid that here (see `sudo service mysql stop` that stops the service and the scripts restarts it later.)?
- I believe we'll need some data for the service, do we already have that in the repo (I could not find any `.sql` file)?
- if the answer to the last one is yes, does it reproduce the unicode error?
I am available tomorrow afternoon if you …
=> First step to spin up a database for testing

docs/WOFpyODM2LBR_installation.md
This fixes documentation problem referenced in https://github.com/ODM2/WOFpy/issues/195 @emiliom
=> update documentation for DAO config file setup.

test/test_config.cfg, wof/core.py, wof/core_1_0.py, wof/core_1_1.py, wof/examples/flask/odm2/timeseries/odm2_config_timeseries.cfg, wof/flask/__init__.py
This PR allows for a custom urlpath so it doesn't need to match the network code.
=> Allow custom urlpath to be specified

wof/core_1_1.py
This PR should address #202. I have found three places within the code where `unitCode` is missing. This element is required based on the WaterML 1.1 schema.
=> Fix missing unitCode element

.travis.yml, appveyor.yml, requirements-dev.txt
@lsetiawan and @emiliom this PR makes use of the conda-forge version of the `odm2` packages. If things are working as expected we can re-add the `flak8-*` in the `requirements-dev.txt ` b/c, without a 3rd channel, we reduce the channel incompatibilities.
=> use conda-forge
